#!groovy

String[] distributions = ['debian:bullseye', 'debian:bookworm', 'ubuntu:jammy']

String vendor = 'vitexsoftware'
String distribution = ''
//String distroFamily = ''
String distroCodename = ''
String ver = ''

properties([
    copyArtifactPermission('*')
])
node() {
    ansiColor('xterm') {
        stage('SCM Checkout') {
            checkout scm
        }
    }
}

distributions.each {
    distribution = it

    println  "Dist:" + distribution

    def dist = distribution.split(':')
    //      distroFamily = dist[0]
    distroCodename = dist[1]

    def buildImage = ''

    node {
        ansiColor('xterm') {
            stage('Checkout ' + distribution) {
                buildImage = docker.image(vendor + '/' + distribution)
		sh 'git checkout debian/changelog'
                def VERSION = sh (
                    script: 'dpkg-parsechangelog --show-field Version',
                    returnStdout: true
                ).trim()
                ver = VERSION + '.' + env.BUILD_NUMBER  + '~' + distroCodename
            }
            stage('Build ' + distribution) {
                buildImage.inside {
                    sh 'dch -b -v ' + ver  + ' "' + env.BUILD_TAG  + '"'
                    sh 'sudo apt-get update --allow-releaseinfo-change'
                    sh 'sudo chown jenkins:jenkins ..'
                    sh 'debuild-pbuilder  -i -us -uc -b'
                    sh 'mkdir -p $WORKSPACE/dist/debian/ ; rm -rf $WORKSPACE/dist/debian/* ; for deb in $(cat debian/files | awk \'{print $1}\'); do mv "../$deb" $WORKSPACE/dist/debian/; done'
                }
            }

            stage('Test ' + distribution) {
                buildImage.inside {
                    def abraflexi_env = 'MATCHER_DAYS_BACK=60 DOCUMENTID=code:PAY_NHZJCY MATCHER_PULL_BANK=true APP_DEBUG=true EASE_LOGGER="console" ABRAFLEXI_URL="https://demo.flexibee.eu:5434" ABRAFLEXI_LOGIN="winstrom" ABRAFLEXI_PASSWORD="winstrom" ABRAFLEXI_COMPANY="demo_de" '
                    def debconf_debug = 0 //Set to "5" or "developer" to debug debconf
                    sh 'cd $WORKSPACE/dist/debian/ ; dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz; cd $WORKSPACE'
                    sh 'echo "deb [trusted=yes] file://///$WORKSPACE/dist/debian/ ./" | sudo tee /etc/apt/sources.list.d/local.list'
                    sh 'sudo apt-get update --allow-releaseinfo-change'
                    sh 'echo "INSTALATION"'
                    sh 'IFS="\n\b"; for package in  `ls $WORKSPACE/dist/debian/ | grep .deb | awk -F_ \'{print \$1}\'` ; do  echo -e "${GREEN} installing ${package} on `lsb_release -sc` ${ENDCOLOR} " ; sudo  DEBIAN_FRONTEND=noninteractive DEBCONF_DEBUG=' + debconf_debug  + ' apt-get -y install $package ; done;'
                    
                    sh abraflexi_env + 'abraflexi-matcher-init'
                    sh abraflexi_env + 'abraflexi-pull-bank'
                    sh abraflexi_env + 'abraflexi-match-bank'
                    //TODO sh abraflexi_env + 'abraflexi-match-cash'
                    sh abraflexi_env + 'abraflexi-matcher'
                    sh abraflexi_env + 'abraflexi-matcher-in'
                    sh abraflexi_env + 'abraflexi-matcher-new2old'
                    sh abraflexi_env + 'abraflexi-matcher-out'
                    
                    stash includes: 'dist/**', name: 'dist-' + distroCodename
                }
            }
            stage('Copy artifacts ' + distribution ) {
                buildImage.inside {
                    sh 'mv $WORKSPACE/dist/debian/*.deb $WORKSPACE'
                }
            }
        }
    }
}

