#!/bin/sh
# postinst script for flexibee-matcher

set -e

    if [ "$1" = "configure" ]; then

    . /usr/share/debconf/confmodule

    fi

db_get composer/WEB_USER
WEBUSER=$RET

mkdir -p /var/lib/composer
chown $WEBUSER:$WEBUSER /var/lib/composer
su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer --no-dev -o install -d /usr/lib/flexibee-matcher/'

php -f /usr/lib/flexibee-matcher/Init.php

#DEBHELPER#

exit 0
