#!/bin/sh
# postinst script for abraflexi-matcher

set -e

. /usr/share/debconf/confmodule












replaceKey() {
    cfg="/etc/abraflexi/matcher.env"
    sed -i "/${1}=/c\        \"${1}\"=${2}" $cfg
}


if [ "$1" = "configure" ]; then
    composer-debian abraflexi-matcher

    KEYS="MATCHER_DAYS_BACK MATCHER_PULL_BANK MATCHER_LABEL_PREPLATEK MATCHER_LABEL_CHYBIFAKTURA MATCHER_LABEL_NEIDENTIFIKOVANO MATCHER_ADD_LOGO MATCHER_LOCALIZE MATCHER_MAIL_CC MATCHER_MAIL_FROM"
    for KEY in $KEYS ; do
	db_get abraflexi-matcher/${KEY}
	replacekey $KEY $RET
    done
    abraflexi-matcher-init
fi


#DEBHELPER#

exit 0
